# pymat

In [1]:
import os,sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append(os.getcwd()+'/build')
import pymat
pymat.HelloWorld()

HelloWorld!


In [2]:
myarray = np.zeros((3))
print(pymat.ArrayF(myarray))
print(myarray)

[1. 1. 1.]
[-1. -1. -1.]


In [3]:
myarray = np.array([0,0,1],dtype=float)
print(pymat.ArrayF(myarray))
print(myarray)

[1. 1. 2.]
[-1. -1.  0.]


**Remark :** It is nessecary to profide the `dtype=....` for a numpy array to be casted correctly down to the c++ level and to be modiefied

## A Matrix Class

In [4]:
# Initialization:
mat = pymat.Matrix(3,3)
mat.print()

0  1  2  
3  4  5  
6  7  8  


A reference cannot be handeled by python as values such as float64 are imutable

In [5]:
# Can I get a the reference to a c-double ?
a = mat.vRef(2,2)
print("Straight from the matrix: ", a)
a = 2
print("After Modification      : ", a)
print("Matrix stays unmodified : ")
mat.print()

Straight from the matrix:  8.0
After Modification      :  2
Matrix stays unmodified : 
     0  1  2  
3  4  5  
6  7  8  


Returning the content of the matrix as numpy array **! data being copied !**

In [6]:
result = mat.ndarray()
print(result)
mat.print()

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
     0  1  2  
3  4  5  
6  7  8  


A direct access, **without copying data** can be made via implementation of the python buffer protocol

In [7]:
test = np.array(mat, copy=False)
print(test)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [8]:
test[1,1] = 10
print(test)
mat.print()

[[ 0.  1.  2.]
 [ 3. 10.  5.]
 [ 6.  7.  8.]]
     0  1  2  
3  10  5  
6  7  8  


# The Matrix **A** example

In [10]:
matA = pymat.MatrixA()
np_matA = np.array(matA, copy=False)